name: cash_flow_facts
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  # flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  fpdart: ^0.6.0
  sqflite: ^2.2.8+4
  form_field_validator: ^1.1.0
  shared_preferences: ^2.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/  
